version: "3.9"
services:
  backend:
    image: strapi/strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: project_miq
      DATABASE_HOST: pgdb
      DATABASE_PORT: 5432
      DATABASE_USERNAME: miq
      DATABASE_PASSWORD: zft3cMAZZR!o
    volumes:
      - ./:/srv/app
    ports:
      - "1337:1337"
    links:
      - pgdb
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    restart: always
    volumes:
      - /project_miq_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: zft3cMAZZR!o
      POSTGRES_USER: miq
      POSTGRES_DB: project_miq

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
