version: "3.9"
services:
  backend:
    build: .
    ports:
      - "1337:1337"
    links:
      - pgdb
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    restart: always
    volumes:
      - /project_miq_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: zft3cMAZZR!o
      POSTGRES_USER: miq
      POSTGRES_DB: project_miq

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
